version: '3.3'
services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'certificator'
      MYSQL_USER: 'certificator'
      MYSQL_PASSWORD: 'certificator'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: